sudo: false
language: php

php:
    - 7.1

before_install:
    - composer self-update
    - composer validate --no-check-all --ansi

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - cd ${TRAVIS_BUILD_DIR}
    - php -l src/
    - ./vendor/bin/phpcs -s --standard=PSR2 ./src/
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - cd ${TRAVIS_BUILD_DIR} && php vendor/bin/coveralls -v
